language: python

services:
  - docker

before_install:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

before_script:
  - sudo service postgresql stop
  - docker-compose up -d

script:
  - docker-compose exec srv ./scripts/entrypoint.sh pytest
  - docker-compose exec srv codecov -t "$CODECOV_TOKEN" -c "$TRAVIS_COMMIT"

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
