language: python

services:
  - docker

before_install:
  - docker-compose build

before_script:
  - sudo service postgresql stop
  - docker-compose up -d

script:
  - docker-compose run --rm --no-deps --entrypoint "" srv pytest
