version: '3'

services:
  srv:
    image: 'mocker'
    env_file:
      - '.env'
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: 'postgres:11'
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

volumes:
  pgdata:
