# Generated by Django 2.2.3 on 2019-08-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseIterator',
            fields=[
                ('mock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mocker.Mock')),
            ],
        ),
        migrations.AlterField(
            model_name='mock',
            name='response_type',
            field=models.CharField(choices=[('cycle', 'cycle'), ('sequence', 'sequence'), ('single', 'single')], default='single', max_length=20),
        ),
        migrations.CreateModel(
            name='ArrayResponseIterator',
            fields=[
                ('responseiterator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mocker.ResponseIterator')),
                ('index', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('mocker.responseiterator',),
        ),
        migrations.CreateModel(
            name='SingleResponseIterator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mocker.responseiterator',),
        ),
        migrations.CreateModel(
            name='CycleResponseIterator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mocker.arrayresponseiterator',),
        ),
        migrations.CreateModel(
            name='SequenceResponseIterator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mocker.arrayresponseiterator',),
        ),
    ]
